themesDir = ".."
theme = "."
locale = "en-us"
baseurl = "https://example.com/"
title = "Hugo Tailwind CSS Starter"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'

author = "Mark Jones"
copyright = "Copyright © 2021, Mark Jones, all rights reserved."

[params]
    name = "Hugo Tailwind CSS Starter"
    description = "A Hugo starter theme with Tailwind CSS 4 and Skeleton UI."

    github_user = "taocode"
    github_repo = "https://github.com/taocode/hugo-theme-tailwindcss-starter"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
